wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.8.5
      5: 0.11.1
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.3
epochs:
  desc: null
  value: 2
fc_layer_size:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.0001
optimizer:
  desc: null
  value: sgd
