wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.1
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      2:
      - 3
      4: 3.8.5
      5: 0.11.1
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 128
dataset:
  desc: null
  value: CIFAR-100
learning_rate:
  desc: null
  value: 0.01
