wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      4: 3.8.5
      5: 0.11.0
      8:
      - 1
      - 3
      - 5
dataset:
  desc: null
  value: ab131
learning_rate:
  desc: null
  value: 0.3
model_architecture:
  desc: null
  value: B
my_param:
  desc: null
  value: 10
params:
  desc: null
  value:
    batch_size: 100
    dropout: 0.5
    learning_rate: 0.001
yaml:
  desc: null
  value:
    Vegetables:
    - Pepper
    - Tomato
    - Garlic
    batch_size:
    - desc: Size of each mini-batch
    - value: 32
    epochs:
    - desc: Number of epochs to train over
    - value: 100
