wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 2
      - 3
      4: 3.8.5
      5: 0.11.1
      8:
      - 1
      - 3
      - 5
architecture:
  desc: null
  value: CNN
batch_size:
  desc: null
  value: 128
classes:
  desc: null
  value: 10
dataset:
  desc: null
  value: MNIST
epochs:
  desc: null
  value: 5
kernels:
  desc: null
  value:
  - 16
  - 32
learning_rate:
  desc: null
  value: 0.005
